# Generated by Django 5.0.3 on 2026-03-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50, verbose_name='职位名称')),
                ('salary', models.CharField(max_length=20, verbose_name='薪资')),
                ('location', models.CharField(max_length=50, verbose_name='工作地点')),
                ('description', models.TextField(verbose_name='职位描述')),
                ('requirements', models.TextField(verbose_name='任职要求')),
                ('audit_status', models.PositiveSmallIntegerField(choices=[(0, '待审核'), (1, '通过'), (2, '驳回'), (3, '下架')], default=0, verbose_name='审核状态')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('collections_count', models.PositiveIntegerField(default=0, verbose_name='收藏量')),
                ('deliveries_count', models.PositiveIntegerField(default=0, verbose_name='投递量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
            },
        ),
    ]
