# Generated by Django 6.0.3 on 2026-03-09 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0008_alter_student_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.company', verbose_name='发布企业'),
        ),
        migrations.AddField(
            model_name='job',
            name='degree_requirement',
            field=models.CharField(choices=[('初中及以下', '初中及以下'), ('高中', '高中'), ('中专/中技', '中专/中技'), ('大专', '大专'), ('本科', '本科'), ('硕士', '硕士'), ('博士', '博士'), ('学历不限', '学历不限')], default='本科', max_length=20, verbose_name='学历要求'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_requirement',
            field=models.CharField(default='不限', max_length=20, verbose_name='经验要求'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='职位分类'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='全职', max_length=20, verbose_name='工作性质'),
        ),
        migrations.AddField(
            model_name='job',
            name='major',
            field=models.CharField(blank=True, max_length=50, verbose_name='专业分类'),
        ),
        migrations.AddField(
            model_name='job',
            name='major_requirement',
            field=models.CharField(blank=True, max_length=50, verbose_name='专业要求'),
        ),
    ]
