# Generated by Django 6.0.3 on 2026-03-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_company_job_degree_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='search_keywords',
            field=models.JSONField(blank=True, default=list, verbose_name='搜索关键词'),
        ),
    ]
