# Generated by Django 6.0.3 on 2026-03-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='degree_requirement',
            field=models.CharField(default='本科', max_length=20, verbose_name='学历要求'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_requirement',
            field=models.CharField(default='不限', max_length=20, verbose_name='经验要求'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='全职', max_length=20, verbose_name='工作性质'),
        ),
    ]
