# Generated by Django 6.0.3 on 2026-03-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_degree_requirement_job_experience_requirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(blank=True, max_length=50, verbose_name='职位分类'),
        ),
        migrations.AddField(
            model_name='job',
            name='major_requirement',
            field=models.CharField(blank=True, max_length=50, verbose_name='专业要求'),
        ),
    ]
