# Generated by Django 6.0.3 on 2026-03-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_search_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='驳回原因'),
        ),
    ]
