# Generated by Django 6.0.3 on 2026-03-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_job_category_job_major_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='degree_requirement',
            field=models.CharField(choices=[('初中及以下', '初中及以下'), ('高中', '高中'), ('中专/中技', '中专/中技'), ('大专', '大专'), ('本科', '本科'), ('硕士', '硕士'), ('博士', '博士'), ('学历不限', '学历不限')], default='本科', max_length=20, verbose_name='学历要求'),
        ),
    ]
