# Generated by Django 6.0.3 on 2026-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_job_category_alter_job_job_category_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(blank=True, db_column='job_category_legacy', max_length=50, verbose_name='职位分类(旧)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='major',
            field=models.CharField(blank=True, db_column='major_legacy', max_length=50, verbose_name='专业分类(旧)'),
        ),
    ]
