# Generated by Django 6.0.3 on 2026-03-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_job_job_category_alter_job_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='major',
        ),
    ]
