# Generated by Django 6.0.3 on 2026-03-13 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_job_job_category_job_major_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='major',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_category_link',
            field=models.ForeignKey(blank=True, db_column='job_category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobcategory', verbose_name='职位分类'),
        ),
        migrations.AlterField(
            model_name='job',
            name='major_link',
            field=models.ForeignKey(blank=True, db_column='major_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.majorcategory', verbose_name='专业分类'),
        ),
    ]
