# Generated by Django 6.0.3 on 2026-03-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_job_job_category_job_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='major',
            field=models.CharField(blank=True, db_column='major_id', max_length=50, verbose_name='专业分类(旧)'),
        ),
    ]
