# Generated by Django 6.0.3 on 2026-03-13 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_alter_job_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_category_link',
        ),
        migrations.RemoveField(
            model_name='job',
            name='major_link',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.ForeignKey(blank=True, db_column='job_category_link_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobcategory', verbose_name='职位分类'),
        ),
        migrations.AlterField(
            model_name='job',
            name='major',
            field=models.ForeignKey(blank=True, db_column='major_link_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.majorcategory', verbose_name='专业分类'),
        ),
    ]
