# Generated by Django 6.0.3 on 2026-03-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_remove_job_job_category_link_remove_job_major_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='takedown_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='下架原因'),
        ),
        migrations.AlterField(
            model_name='job',
            name='audit_status',
            field=models.PositiveSmallIntegerField(choices=[(0, '待审核'), (1, '通过'), (2, '驳回'), (3, '下架'), (4, '申请下架')], default=0, verbose_name='审核状态'),
        ),
    ]
