# Generated by Django 5.0.3 on 2026-03-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='推荐得分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='jobs.job', verbose_name='推荐职位')),
            ],
            options={
                'verbose_name': '推荐结果',
                'verbose_name_plural': '推荐结果',
                'ordering': ['-score'],
            },
        ),
    ]
