# Generated by Django 5.0.3 on 2026-03-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.student', verbose_name='推荐学生'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['student', '-score'], name='recommendat_student_d3680a_idx'),
        ),
    ]
