# Generated by Django 6.0.3 on 2026-03-14 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_remove_job_job_category_link_remove_job_major_link_and_more'),
        ('recommendation', '0002_initial'),
        ('users', '0013_student_job_intention'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(verbose_name='相似度')),
                ('co_cnt', models.PositiveIntegerField(default=0, verbose_name='共同交互用户数')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '推荐-岗位相似度',
                'verbose_name_plural': '推荐-岗位相似度',
            },
        ),
        migrations.CreateModel(
            name='UserItemScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='最终分数')),
                ('view_cnt', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('collect_cnt', models.PositiveIntegerField(default=0, verbose_name='收藏次数')),
                ('deliver_cnt', models.PositiveIntegerField(default=0, verbose_name='投递次数')),
                ('last_action_time', models.DateTimeField(auto_now=True, verbose_name='最后交互时间')),
            ],
            options={
                'verbose_name': '推荐-用户评分聚合',
                'verbose_name_plural': '推荐-用户评分聚合',
            },
        ),
        migrations.CreateModel(
            name='UserSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(verbose_name='相似度')),
                ('co_cnt', models.PositiveIntegerField(default=0, verbose_name='共同交互岗位数')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '推荐-用户相似度',
                'verbose_name_plural': '推荐-用户相似度',
            },
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name': '推荐结果', 'verbose_name_plural': '推荐结果'},
        ),
        migrations.RemoveIndex(
            model_name='recommendation',
            name='recommendat_student_d3680a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('student', 'job')},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='reason',
            field=models.JSONField(blank=True, null=True, verbose_name='推荐理由'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='score_hybrid',
            field=models.FloatField(default=0.0, verbose_name='混合分数'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='score_item',
            field=models.FloatField(default=0.0, verbose_name='Item-based分数'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='score_user',
            field=models.FloatField(default=0.0, verbose_name='User-based分数'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.student', verbose_name='学生'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['student', '-score_hybrid'], name='recommendat_student_be5dff_idx'),
        ),
        migrations.AddField(
            model_name='itemsimilarity',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_source', to='jobs.job', verbose_name='主岗位'),
        ),
        migrations.AddField(
            model_name='itemsimilarity',
            name='sim_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_target', to='jobs.job', verbose_name='相似岗位'),
        ),
        migrations.AddField(
            model_name='useritemscore',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='useritemscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='usersimilarity',
            name='sim_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sim_target', to='users.student', verbose_name='相似学生'),
        ),
        migrations.AddField(
            model_name='usersimilarity',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sim_source', to='users.student', verbose_name='学生'),
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='score',
        ),
        migrations.AddIndex(
            model_name='itemsimilarity',
            index=models.Index(fields=['job', '-similarity'], name='recommendat_job_id_62a5a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemsimilarity',
            unique_together={('job', 'sim_job')},
        ),
        migrations.AddIndex(
            model_name='useritemscore',
            index=models.Index(fields=['student', 'job'], name='recommendat_student_4f8200_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useritemscore',
            unique_together={('student', 'job')},
        ),
        migrations.AddIndex(
            model_name='usersimilarity',
            index=models.Index(fields=['student', '-similarity'], name='recommendat_student_77f57d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersimilarity',
            unique_together={('student', 'sim_student')},
        ),
    ]
