# Generated by Django 6.0.3 on 2026-03-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=50, verbose_name='所属行业'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='企业Logo'),
        ),
        migrations.AddField(
            model_name='company',
            name='nature',
            field=models.CharField(blank=True, max_length=50, verbose_name='企业性质'),
        ),
        migrations.AddField(
            model_name='company',
            name='scale',
            field=models.CharField(blank=True, max_length=50, verbose_name='人员规模'),
        ),
    ]
