# Generated by Django 6.0.3 on 2026-03-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_industry_company_logo_company_nature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=50, verbose_name='学校'),
        ),
    ]
