# Generated by Django 6.0.3 on 2026-03-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, verbose_name='头像URL'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='电话号码'),
        ),
    ]
