# Generated by Django 6.0.3 on 2026-03-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='company_logos/', verbose_name='企业Logo'),
        ),
    ]
