# Generated by Django 6.0.3 on 2026-03-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Administrator'), (1, 'Student'), (2, 'Company')], default=1, verbose_name='角色'),
        ),
    ]
