# Generated by Django 6.0.3 on 2026-03-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='驳回原因'),
        ),
    ]
