# Generated by Django 6.0.3 on 2026-03-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_company_reject_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='行业名称')),
                ('description', models.TextField(blank=True, verbose_name='行业描述')),
            ],
            options={
                'verbose_name': '行业信息',
                'verbose_name_plural': '行业信息',
            },
        ),
    ]
