# Generated by Django 6.0.3 on 2026-03-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='job_intention',
            field=models.CharField(blank=True, max_length=50, verbose_name='求职意向'),
        ),
    ]
