# Generated by Django 5.0.3 on 2026-03-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未查看'), (1, '已查看'), (2, '有意向'), (3, '不合适')], default=0, verbose_name='申请状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='投递时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '职位申请',
                'verbose_name_plural': '职位申请',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(max_length=50, verbose_name='简历名称')),
                ('content', models.JSONField(verbose_name='简历内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
            },
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_type', models.PositiveSmallIntegerField(choices=[(1, '浏览'), (2, '收藏'), (3, '投递')], verbose_name='行为类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='行为时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='职位')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
            },
        ),
    ]
