# Generated by Django 6.0.3 on 2026-03-09 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_company_job_degree_requirement_and_more'),
        ('recruitment', '0001_initial'),
        ('users', '0008_alter_student_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavior',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job', verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.resume', verbose_name='投递简历'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='resume',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='users.student', verbose_name='所属学生'),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='职位'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('student', 'job')},
        ),
        migrations.AddIndex(
            model_name='behavior',
            index=models.Index(fields=['student', 'job'], name='recruitment_student_5f90a8_idx'),
        ),
    ]
