# Generated by Django 6.0.3 on 2026-03-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_jobapplication_status_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='recruitment.jobapplication', verbose_name='关联申请'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未查看'), (1, '已查看'), (2, '有意向'), (3, '不合适')], default=0, verbose_name='申请状态'),
        ),
    ]
