# Generated by Django 6.0.3 on 2026-03-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_alter_chatmessage_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未查看'), (1, '已查看'), (2, '有意向'), (3, '不合适'), (4, '通过')], default=0, verbose_name='申请状态'),
        ),
    ]
