# Generated by Django 6.0.3 on 2026-03-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未查看'), (1, '已查看'), (2, '面试中'), (3, '不合适'), (4, '通过'), (5, '不通过')], default=0, verbose_name='申请状态'),
        ),
    ]
