# Generated by Django 6.0.3 on 2026-03-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='是否推荐投递'),
        ),
    ]
