# Generated by Django 6.0.3 on 2026-03-18 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_jobapplication_is_recommended'),
        ('users', '0013_student_job_intention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='users.student', verbose_name='学生'),
        ),
    ]
